/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button.vue')['default']
    'IMaterialSymbols:search': typeof import('~icons/material-symbols/search')['default']
    LayoutHapusAkun: typeof import('./src/components/layout/hapus-akun.vue.vue')['default']
    LayoutSidebar: typeof import('./src/components/layout/sidebar.vue')['default']
    LayoutSiderbarAdmin: typeof import('./src/components/layout/siderbarAdmin.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NInpbgut: typeof import('naive-ui')['NInpbgut']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NTable: typeof import('naive-ui')['NTable']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./src/components/ui/button.vue')['default']
    UiButtonExample: typeof import('./src/components/ui/button-example.vue')['default']
  }
}
