/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComponenUserEditProfilAnak: typeof import('./src/components/componen-user/edit-profil-anak.vue')['default']
    ComponenUserEditProfilChild: typeof import('./src/components/componen-user/edit-profil-child.vue')['default']
    IFeArrowLeft: typeof import('~icons/fe/arrow-left')['default']
    'IIc:baselineHome': typeof import('~icons/ic/baseline-home')['default']
    'IIc:outlineMessage': typeof import('~icons/ic/outline-message')['default']
    'IIc:roundPhone': typeof import('~icons/ic/round-phone')['default']
    'ILucide:fileChartLine': typeof import('~icons/lucide/file-chart-line')['default']
    'IMage:dots': typeof import('~icons/mage/dots')['default']
    'IMaterialSymbols:articleOutline': typeof import('~icons/material-symbols/article-outline')['default']
    'IMaterialSymbols:search': typeof import('~icons/material-symbols/search')['default']
    'IMdi:addressMarker': typeof import('~icons/mdi/address-marker')['default']
    'IPrime:addressBook': typeof import('~icons/prime/address-book')['default']
    'IUil:calender': typeof import('~icons/uil/calender')['default']
    LayoutHeader: typeof import('./src/components/layout/header.vue')['default']
    LayoutNavbar: typeof import('./src/components/layout/navbar.vue')['default']
    LayoutSidebar: typeof import('./src/components/layout/sidebar.vue')['default']
    LayoutSidebarmobile: typeof import('./src/components/layout/sidebarmobile.vue')['default']
    LayoutSiderbarAdmin: typeof import('./src/components/layout/siderbarAdmin.vue')['default']
    ModalInputUserEditDataChild: typeof import('./src/components/modal/input-user/edit-data-child.vue')['default']
    ModalInputUserInputDataChild: typeof import('./src/components/modal/input-user/input-data-child.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPagination: typeof import('naive-ui')['NPagination']
    NSelect: typeof import('naive-ui')['NSelect']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NUpload: typeof import('naive-ui')['NUpload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiAvatar: typeof import('./src/components/ui/avatar.vue')['default']
    UiButton: typeof import('./src/components/ui/button.vue')['default']
  }
}
